[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["T201"]  # Ignore T201 (print found) since this is a CLI tool

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"
